global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dean-system'

scrape_configs:
  # DEAN API metrics
  - job_name: 'dean-api'
    static_configs:
      - targets: ['dean-api:8091']
    metrics_path: '/metrics'

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter (if added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Airflow metrics
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    metrics_path: '/admin/metrics'

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']